Attaching to backend_db_1, backend_server_1
[36mdb_1      |[0m 
[36mdb_1      |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[36mdb_1      |[0m 
[36mdb_1      |[0m 2021-06-17 21:57:00.428 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
[36mdb_1      |[0m 2021-06-17 21:57:00.428 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[36mdb_1      |[0m 2021-06-17 21:57:00.428 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[36mdb_1      |[0m 2021-06-17 21:57:00.489 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1      |[0m 2021-06-17 21:57:00.677 UTC [21] LOG:  database system was shut down at 2021-06-17 21:56:55 UTC
[36mdb_1      |[0m 2021-06-17 21:57:00.703 UTC [1] LOG:  database system is ready to accept connections
[33mserver_1  |[0m INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[33mserver_1  |[0m INFO:     Started reloader process [1]
[33mserver_1  |[0m File:server.py Before imports
[33mserver_1  |[0m Process SpawnProcess-1:
[33mserver_1  |[0m Traceback (most recent call last):
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
[33mserver_1  |[0m     self.run()
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
[33mserver_1  |[0m     self._target(*self._args, **self._kwargs)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
[33mserver_1  |[0m     target(sockets=sockets)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
[33mserver_1  |[0m     loop.run_until_complete(self.serve(sockets=sockets))
[33mserver_1  |[0m   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
[33mserver_1  |[0m     config.load()
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
[33mserver_1  |[0m     self.loaded_app = import_from_string(self.app)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
[33mserver_1  |[0m     raise exc from None
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
[33mserver_1  |[0m     module = importlib.import_module(module_str)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[33mserver_1  |[0m     return _bootstrap._gcd_import(name[level:], package, level)
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[33mserver_1  |[0m   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[33mserver_1  |[0m   File "./src/api/server.py", line 5, in <module>
[33mserver_1  |[0m     from src.core import config,tasks
[33mserver_1  |[0m   File "./src/core/tasks.py", line 4, in <module>
[33mserver_1  |[0m     from src.db.tasks import connect_to_db, close_db_connection
[33mserver_1  |[0m   File "./src/db/tasks.py", line 1, in <module>
[33mserver_1  |[0m     from backend import src
[33mserver_1  |[0m ModuleNotFoundError: No module named 'backend'
[33mserver_1  |[0m WARNING:  Detected file change in 'src/api/server.py'. Reloading...
[33mserver_1  |[0m File:server.py Before imports
[33mserver_1  |[0m Process SpawnProcess-2:
[33mserver_1  |[0m Traceback (most recent call last):
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
[33mserver_1  |[0m     self.run()
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
[33mserver_1  |[0m     self._target(*self._args, **self._kwargs)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
[33mserver_1  |[0m     target(sockets=sockets)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
[33mserver_1  |[0m     loop.run_until_complete(self.serve(sockets=sockets))
[33mserver_1  |[0m   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
[33mserver_1  |[0m     config.load()
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
[33mserver_1  |[0m     self.loaded_app = import_from_string(self.app)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
[33mserver_1  |[0m     raise exc from None
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
[33mserver_1  |[0m     module = importlib.import_module(module_str)
[33mserver_1  |[0m   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
[33mserver_1  |[0m     return _bootstrap._gcd_import(name[level:], package, level)
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[33mserver_1  |[0m   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[33mserver_1  |[0m   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[33mserver_1  |[0m   File "./src/api/server.py", line 5, in <module>
[33mserver_1  |[0m     from src.core import config,tasks
[33mserver_1  |[0m   File "./src/core/tasks.py", line 4, in <module>
[33mserver_1  |[0m     from src.db.tasks import connect_to_db, close_db_connection
[33mserver_1  |[0m   File "./src/db/tasks.py", line 1, in <module>
[33mserver_1  |[0m     from backend import src
[33mserver_1  |[0m ModuleNotFoundError: No module named 'backend'
[33mserver_1  |[0m INFO:     Stopping reloader process [1]
[33mbackend_server_1 exited with code 0
[0m[36mdb_1      |[0m 2021-06-17 22:07:28.767 UTC [1] LOG:  received fast shutdown request
[36mdb_1      |[0m 2021-06-17 22:07:28.794 UTC [1] LOG:  aborting any active transactions
[36mdb_1      |[0m 2021-06-17 22:07:28.795 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
[36mdb_1      |[0m 2021-06-17 22:07:28.795 UTC [22] LOG:  shutting down
[36mdb_1      |[0m 2021-06-17 22:07:28.992 UTC [1] LOG:  database system is shut down
[36mbackend_db_1 exited with code 0
[0m